# Generated by Django 4.0.5 on 2022-06-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='No notes were provided'),
        ),
        migrations.AlterField(
            model_name='books',
            name='desc',
            field=models.TextField(default='No description was provided.'),
        ),
    ]
