# Generated by Django 4.0.5 on 2022-06-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthors', '0002_authors_notes_alter_books_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='created',
        ),
        migrations.AddField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='booksAuthors.books'),
        ),
    ]
