# Generated by Django 4.0.5 on 2022-06-23 09:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wishApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='Addedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wish', to='wishApp.user'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='item',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
