# Generated by Django 4.0.5 on 2022-06-23 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishApp', '0002_wishlist_addedby_wishlist_dateadded_wishlist_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='Addedby',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='wish', to='wishApp.user'),
            preserve_default=False,
        ),
    ]
