# Generated by Django 4.0.5 on 2022-06-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishApp', '0003_alter_wishlist_addedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='user_fav',
            field=models.ManyToManyField(related_name='fav_items', to='wishApp.user'),
        ),
    ]
