# Generated by Django 4.0.5 on 2022-06-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegistration', '0003_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
