# Generated by Django 4.0.5 on 2022-06-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegistration', '0004_remove_user_id_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(default='https://www.w3schools.com/howto/img_avatar.png'),
        ),
    ]
